language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
# command to run tests
script: py.test --doctest-modules pyATK/ --cov=pyATK/

install:
  - pip install pytest pytest-cov
  - pip install coveralls
after_success:
  - coveralls
